Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Metrics/BlockLength:
  Max: 60

Style/HashEachMethods:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 120

AllCops:
  Exclude:
    - bin/**/*
    - vendor/**/*
    - log/**/*
    - tmp/**/*
    - assets/**/*
    - spec/**/*

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Lint/DuplicateElsifCondition:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true
